---
title: "HerringTest"
author: "Tim Cashion"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: github_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(knitr)
library(tidyverse)
library(hrbrthemes)
library(bookdown)
library(plotly)
source("./R/cpi_function.R")
cpi <- read_csv("./Data/Canadian_CPI.csv") %>% 
  mutate(base_year=2002) %>% 
  select(-InflationRate)
cpi_2015 <- inflation_adjust(cpi, 2015) %>% 
  rename(Year=year)
theme_set(theme_ipsum()) # Doesn't work on PC because it's missing Arial Narrow font.
#theme_set(theme_ipsum_rc())

number_call <- function(num, decimals){
  x <- prettyNum(num, big.mark = ",", small.mark = ".", digits=decimals) 
  return(x)
}

```


```{r catch-by-type, echo=F, warning=F, message=F, fig.cap="Catch of herring by fishery type"}
##Plots of catch, landed value, and wholesale values
fisherytype_value <- read_csv("./Data/HerringValueFisheries.csv")
fisherytype_value <- fisherytype_value %>%
  mutate_if(is.character, as.factor) %>%
  filter(Fishery != "Total") %>% 
  left_join(cpi_2015) %>% 
  mutate(Value= if_else(str_detect(Measure, pattern=" value"), Value*adj_value, Value))

fisherytype_value_plot <- fisherytype_value %>%
  filter(Measure=="Landings") %>% 
  ggplot(aes(x=Year,y=Value, group=Fishery, color=Fishery)) +
  geom_line() +
  ylab("Landings (thousand tonnes)") + 
  scale_y_continuous(expand=c(0,0)) + 
  scale_x_continuous(labels=c(seq(2001, 2018, 4)), expand=c(0,0)) +
  scale_color_ipsum() + 
  NULL

print(fisherytype_value_plot)
# p <- ggplotly(fisherytype_value_plot)
# p


```

